name: Test CI

on:
  push:
    branches: [ "main", "GET-1465" ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env: # Or as an environment variable
  TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
  TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
  TEST_MERCHANT_ID: ${{ secrets.TEST_MERCHANT_ID }}
  TEST_WEGETFINANCING_URL: ${{ secrets.TEST_WEGETFINANCING_URL }}

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
      - name: Trim dependency
        run: composer remove --dev phpmd/phpmd phpstan/phpstan squizlabs/php_codesniffer friendsofphp/php-cs-fixer
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run test suite
        run: |
          php --version
          composer test
